### PR TITLE
'foo.bar'->hasPermission('foo.*') should return false, fixes #541

### LINKED ISSUE #541: 'foo.bar'->hasPermission('foo.*') should return false
If a user has the permission 'foo.bar' then a check against `hasPermission('foo.*')` should return `false` IMO since the latter implies that the user has access to everything under `foo` which isn't the case. I suspect this is a bug since a user with `'foo.bar'` should not have access to all resources under `'foo'` and especially not `'foo.*'`.

The implementation references #123 but that was more about giving user access to `foo.*` and checking if `'foo.*'->hasPermission('foo.bar')` should return true, which Sentry already does.

### PR DESCRIPTION
**Pull request by aleemb**
@brunogaspar as per #541

### CODE REVIEW

**Comment by brunogaspar** [comment]
You've updated the name of the package on the `composer.json`, which you shouldn't.

But i don't believe i'll be able to merge this, while it fixes the behaviour it introduces a breaking change..

**Comment by aleemb** [comment]
Yeah I did a commit after the PR which the PR automatically seems to have picked up.

Fair enough comment re breaking changes. Closing this off, will work off my branch for now.

Look forward to Sentinel release.

Cheers!

**Comment by brunogaspar** [comment]
@aleemb Sentinel is already open source.

**Comment by MangoMM** [comment]
Hello!

 

Check it out http://miamidadebaseball.com/came.php?rwxm

 

ahmet@mangomm.co.uk

**Pull request closed without merging**
